#!/usr/bin/env bash

set -ouex pipefail

LOCAL_BIN_DIR=${HOME}/.local/bin

[[ -d ${LOCAL_BIN_DIR} ]] || mkdir -p "${LOCAL_BIN_DIR}"

curl -fLo "${LOCAL_BIN_DIR}"/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm && chmod a+x "${LOCAL_BIN_DIR}"/yadm

yadm clone -f https://github.com/joshuadavidthomas/dotfiles
