version = 1

[settings]
bin_path = "/home/josh/.local/bin"
always_use_raw = false

[aliases.lT]
command = "eza --tree --git-ignore --level=4 --group-directories-first"

[aliases.ll]
command = "eza --long --all --group-directories-first --git"

[aliases.ls]
command = "eza"

[aliases.lt]
command = "eza --tree --git-ignore --level=2 --group-directories-first"

[aliases.tree]
command = "eza --tree"

[aliases.top]
command = "btop"

[aliases.lg]
command = "TERM=xterm-256color lazygit"

[aliases.vim]
command = "nvim"

[aliases.llt]
command = "eza --long --tree --git-ignore --level=2 --group-directories-first"

[aliases.l]
command = "eza --long --all --group-directories-first --git-ignore"

[aliases.la]
command = "eza --long --all --git"
