#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$0")/../common/utils.sh"

yay -S --noconfirm --needed \
        cargo \
        clang \
        github-cli \
        imagemagick \
        lazydocker \
        lazygit \
        llvm \
        mise \
        postgresql-libs
