#!/bin/bash

cd "$HOME"

# permissions
chmod 700 ~/.cache ~/.config

# sparse checkout
yadm gitconfig core.sparseCheckout true
yadm sparse-checkout set '/*' '!README.md' '!LICENSE' '!.github/workflows/*'
