#!/usr/bin/bash

set -oue pipefail

source "$(dirname "$0")/utils.sh"

check_command flatpak

if [ -f "$HOME/.flatpaks" ]; then
        xargs -a "$HOME/.flatpaks" -r flatpak --system -y install --or-update
fi
