#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$0")/../utils"

sudo pacman -S --needed --noconfirm \
        base-devel \
        git

command -v yay >/dev/null 2>&1 || {
        git clone https://aur.archlinux.org/yay.git /tmp/yay
        cd /tmp/yay
        makepkg -si --noconfirm
        cd -
        rm -rf /tmp/yay
}
