#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$0")/../utils"

check_root "$@"

# dependencies for building yay
sudo pacman -S --needed --noconfirm git base-devel

check_command yay || {
        git clone https://aur.archlinux.org/yay.git /tmp/yay
        cd /tmp/yay
        sudo -u "$SUDO_USER" makepkg -si --noconfirm
        cd -
        rm -rf /tmp/yay
}
