#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$0")/../utils"

yay -S --noconfirm --needed gnupg
gpg --keyserver keyserver.ubuntu.com --receive-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22

yay -S --noconfirm --needed \
        1password-cli \
        blueberry \
        btop \
        cups \
        cups-filters \
        cups-pdf \
        curl \
        inetutils \
        keyd \
        man \
        power-profiles-daemon \
        python-gobject \
        rclone \
        unzip \
        wget \
        zip

sudo systemctl enable --now bluetooth.service
sudo systemctl enable --now cups.service
sudo systemctl enable --now keyd.service

sudo mkdir -p /etc/keyd
cat <<EOF | sudo tee /etc/keyd/default.conf >/dev/null
[ids]

*

[main]

# Maps capslock to escape when pressed and control when held
capslock = overload(control, esc)

# Remaps the escape key to capslock
esc = capslock

# Creates special vim layer when 'control+shift' is held
[control+shift]

h = left
k = up
j = down
l = right
EOF

# Setting the performance profile can make a big difference. By default, most systems seem to start in balanced mode,
# even if they're not running off a battery. So let's make sure that's changed to performance.
# if ls /sys/class/power_supply/BAT* &>/dev/null; then
#         # This computer runs on a battery
#         powerprofilesctl set balanced
# else
#         # This computer runs on power outlet
#         powerprofilesctl set performance
# fi
