#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$0")/../utils"

sudo pacman -S --needed --noconfirm git base-devel

command -v yay >/dev/null 2>&1 || {
        git clone https://aur.archlinux.org/yay.git /tmp/yay
        cd /tmp/yay
        makepkg -si --noconfirm
        cd -
        rm -rf /tmp/yay
}

yay -S --noconfirm --needed \
        blueberry \
        btop \
        cups \
        cups-filters \
        cups-pdf \
        curl \
        inetutils \
        keyd \
        man \
        power-profiles-daemon \
        python-gobject \
        unzip \
        wget

sudo systemctl enable --now keyd.service
sudo systemctl enable --now bluetooth.service
sudo systemctl enable --now cups.service

# Setting the performance profile can make a big difference. By default, most systems seem to start in balanced mode,
# even if they're not running off a battery. So let's make sure that's changed to performance.
# if ls /sys/class/power_supply/BAT* &>/dev/null; then
#         # This computer runs on a battery
#         powerprofilesctl set balanced
# else
#         # This computer runs on power outlet
#         powerprofilesctl set performance
# fi
