#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$0")/../utils"

sudo pacman -S --needed --noconfirm git base-devel

check_command yay || {
        git clone https://aur.archlinux.org/yay.git /tmp/yay
        cd /tmp/yay
        makepkg -si --noconfirm
        cd -
        rm -rf /tmp/yay
}
