#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$0")/../utils"

yay -S --noconfirm --needed \
        curl \
        keyd \
        power-profiles-daemon \
        python-gobject \
        unzip

# Enable keyd service
if pacman -Qq keyd &>/dev/null; then
        systemctl enable --now keyd || true
fi

# Setting the performance profile can make a big difference. By default, most systems seem to start in balanced mode,
# even if they're not running off a battery. So let's make sure that's changed to performance.
# if ls /sys/class/power_supply/BAT* &>/dev/null; then
#         # This computer runs on a battery
#         powerprofilesctl set balanced
# else
#         # This computer runs on power outlet
#         powerprofilesctl set performance
# fi
