#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$1")/../utils"

yay -S --noconfirm --needed \
        atuin \
        bat \
        btop \
        curl \
        direnv \
        eza \
        fastfetch \
        fd \
        flyctl \
        fzf \
        git-delta \
        github-cli \
        inetutils \
        jq \
        just \
        lazydocker \
        lazygit \
        less \
        llvm \
        man \
        neovim \
        plocate \
        ripgrep \
        starship \
        tailscale \
        tldr \
        unzip \
        wget \
        whois \
        zoxide
