#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$0")/../utils"

yay -S --noconfirm --needed \
        atuin \
        bat \
        btop \
        clipse \
        eza \
        fastfetch \
        fd \
        fish \
        fzf \
        git-delta \
        less \
        neovim \
        plocate \
        ripgrep \
        starship \
        tailscale \
        whois \
        wl-clip-persist \
        wl-clipboard \
        zoxide

(cd "$(bat --config-dir)" && ./update-themes)

# Login to Atuin if not already logged in and 1Password is available
if ! (command -v op &>/dev/null && atuin status 2>&1 | grep -q "Username:"); then
        ATUIN_BASE_OP_URI="op://Dunbrook Web/Atuin"
        ATUIN_PASSWORD=$(op read "$ATUIN_BASE_OP_URI/password" 2>/dev/null || echo "")
        ATUIN_KEY=$(op read "$ATUIN_BASE_OP_URI/key" 2>/dev/null || echo "")

        if [[ -n "$ATUIN_PASSWORD" ]] && [[ -n "$ATUIN_KEY" ]]; then
                atuin login -u "josh" -p "$ATUIN_PASSWORD" -k "$ATUIN_KEY"
        fi
fi

NEOVIM_CONFIG_DIR="$HOME/.config/nvim"
rm -rf "$NEOVIM_CONFIG_DIR"
git clone https://github.com/joshuadavidthomas/nvim "$NEOVIM_CONFIG_DIR"

PROJECTS_DIR="$HOME/projects"
mkdir -p "$PROJECTS_DIR"
# this is private for now
# git clone https://github.com/joshuadavidthomas/spotify.nvim "$PROJECTS_DIR/spotify.nvim"
git clone https://github.com/joshuadavidthomas/tokyonight.nvim "$PROJECTS_DIR/tokyonight.nvim"
