#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$0")/../utils"

yay -S --noconfirm --needed \
        atuin \
        bat \
        btop \
        clipse \
        eza \
        fastfetch \
        fd \
        fish \
        fzf \
        git-delta \
        less \
        neovim \
        plocate \
        ripgrep \
        starship \
        tailscale \
        whois \
        wl-clip-persist \
        wl-clipboard \
        zoxide

(cd "$(bat --config-dir)" && ./update-themes)

if [[ -n "${ATUIN_PASSWORD:-}" ]] && [[ -n "${ATUIN_KEY:-}" ]]; then
        atuin login -u "josh" -p "$ATUIN_PASSWORD" -k "$ATUIN_KEY"
fi

rm -rf ~/.config/nvim
git clone https://github.com/joshuadavidthomas/nvim ~/.config/nvim
