#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$1")/../utils"

BACKGROUNDS_DIR=~/.local/share/backgrounds/

mkdir -p "$BACKGROUNDS_DIR/tokyo-night"

curl -sL -o "$BACKGROUNDS_DIR/tokyo-night/1-Pawel-Czerwinski-Abstract-Purple-Blue.jpg" https://images.unsplash.com/photo-1651870364199-fc5f9f46ac85
curl -sL -o "$BACKGROUNDS_DIR/tokyo-night/2-Milad-Fakurian-Abstract-Purple-Blue.jpg" https://images.unsplash.com/photo-1620207418302-439b387441b0
