#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$0")/../utils"

yay -S --noconfirm --needed \
        blueberry \
        brightnessctl \
        cups \
        cups-filters \
        cups-pdf \
        evince \
        file-roller \
        gnome-calculator \
        gnome-themes-extra \
        hypridle \
        hyprland \
        hyprland-qtutils \
        hyprlock \
        hyprpaper \
        hyprpicker \
        hyprpolkitagent \
        hyprshot \
        imv \
        kvantum-qt5 \
        nautilus \
        pamixer \
        pavucontrol \
        playerctl \
        qt5-wayland \
        qt6-wayland \
        swaync \
        sushi \
        system-config-printer \
        waybar \
        wireplumber \
        wofi \
        xdg-desktop-portal-hyprland \
        xdg-desktop-portal-gtk

gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

# Start Hyprland on first session
echo "[[ -z \$DISPLAY && \$(tty) == /dev/tty1 ]] && exec Hyprland" >~/.bash_profile

# Turn on bluetooth by default
sudo systemctl enable --now bluetooth.service

sudo systemctl enable --now cups.service
