#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$0")/../utils"

yay -Sy --noconfirm --needed \
        adobe-source-code \
        inter-font \
        noto-fonts \
        noto-fonts-cjk \
        noto-fonts-emoji \
        noto-fonts-extra \
        ttf-dejavu \
        ttf-fira-code \
        ttf-font-awesome \
        ttf-hack \
        ttf-jetbrains-mono \
        ttf-liberation \
        ttf-nerd-fonts-symbols \
        ttf-nerd-fonts-symbols-mono \
        ttf-roboto \
        ttf-symbols

mkdir -p ~/.local/share/fonts

if ! fc-list | grep -qi "CaskaydiaMono Nerd Font"; then
        cd /tmp
        wget https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaMono.zip
        unzip CascadiaMono.zip -d CascadiaFont
        cp CascadiaFont/CaskaydiaMonoNerdFont-Regular.ttf ~/.local/share/fonts
        cp CascadiaFont/CaskaydiaMonoNerdFont-Bold.ttf ~/.local/share/fonts
        cp CascadiaFont/CaskaydiaMonoNerdFont-Italic.ttf ~/.local/share/fonts
        cp CascadiaFont/CaskaydiaMonoNerdFont-BoldItalic.ttf ~/.local/share/fonts
        rm -rf CascadiaMono.zip CascadiaFont
        cd -
fi

if ! fc-list | grep -qi "iA Writer Mono S"; then
        cd /tmp
        wget -O iafonts.zip https://github.com/iaolo/iA-Fonts/archive/refs/heads/master.zip
        unzip iafonts.zip -d iaFonts
        cp iaFonts/iA-Fonts-master/iA\ Writer\ Mono/Static/iAWriterMonoS-*.ttf ~/.local/share/fonts
        rm -rf iafonts.zip iaFonts
        cd -
fi

fc-cache -fv
