#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$0")/../utils"

yay -S --noconfirm --needed \
        chromium \
        firefox \
        vivaldi

mkdir -p "$HOME/.local/share/applications"

cp /usr/share/applications/chromium.desktop "$HOME/.local/share/applications"
sed -i 's|^Exec=/usr/bin/chromium %U$|Exec=/usr/bin/chromium --enable-features=UseOzonePlatform --ozone-platform=wayland %U|' ~/.local/share/applications/chromium.desktop
sed -i 's|^Exec=/usr/bin/chromium$|Exec=/usr/bin/chromium --enable-features=UseOzonePlatform --ozone-platform=wayland|' ~/.local/share/applications/chromium.desktop
sed -i 's|^Exec=/usr/bin/chromium --incognito$|Exec=/usr/bin/chromium --enable-features=UseOzonePlatform --ozone-platform=wayland --incognito|' ~/.local/share/applications/chromium.desktop

cp /usr/share/applications/vivaldi-stable.desktop "$HOME/.local/share/applications"
sed -i 's|^Exec=/usr/bin/vivaldi-stable %U$|Exec=/usr/bin/vivaldi-stable --enable-features=UseOzonePlatform --ozone-platform=wayland %U|' ~/.local/share/applications/vivaldi-stable.desktop
sed -i 's|^Exec=/usr/bin/vivaldi-stable --new-window$|Exec=/usr/bin/vivaldi-stable --enable-features=UseOzonePlatform --ozone-platform=wayland --new-window|' ~/.local/share/applications/vivaldi-stable.desktop
sed -i 's|^Exec=/usr/bin/vivaldi-stable --incognito$|Exec=/usr/bin/vivaldi-stable --enable-features=UseOzonePlatform --ozone-platform=wayland --incognito|' ~/.local/share/applications/vivaldi-stable.desktop

xdg-settings set default-web-browser vivaldi-stable.desktop
