#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$1")/../utils"

yay -S --noconfirm --needed \
        direnv \
        docker \
        docker-compose \
        flyctl \
        github-cli \
        just \
        lazydocker \
        lazygit \
        llvm \
        mise \
        tldr

# Limit log size to avoid running out of disk
echo '{"log-driver":"json-file","log-opts":{"max-size":"10m","max-file":"5"}}' | sudo tee /etc/docker/daemon.json

# Start Docker automatically
sudo systemctl enable docker

# Give this user privileged Docker access
sudo usermod -aG docker ${USER}
