#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$0")/../utils"

yay -S --noconfirm --needed \
        1password \
        evince \
        file-roller \
        gnome-calculator \
        libreoffice-fresh \
        nautilus \
        obs-studio \
        obsidian \
        signal-desktop \
        slack-desktop \
        spotify \
        sushi \
        teams-for-linux \
        typora \
        vlc \
        webcord \
        xournalpp \
        zoom

sudo mkdir -p /etc/1password
cat <<EOF | sudo tee /etc/1password/custom_allowed_browsers >/dev/null
vivaldi-bin
EOF

mkdir -p "$HOME/.local/share/applications"

cp /usr/share/applications/spotify.desktop "$HOME/.local/share/applications"
sed -i 's|^Exec=spotify --uri=%u|Exec=spotify --enable-features=UseOzonePlatform --ozone-platform=wayland --uri=%u|' ~/.local/share/applications/spotify.desktop

# if ! command -v spicetify &>/dev/null; then
#         curl -fsSL https://raw.githubusercontent.com/spicetify/cli/main/install.sh | sh
#         curl -fsSL https://raw.githubusercontent.com/spicetify/marketplace/main/resources/install.sh | sh
# fi
