#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$0")/../utils"

yay -S --noconfirm --needed \
        1password \
        1password-cli \
        evince \
        file-roller \
        gnome-calculator \
        libreoffice-fresh \
        nautilus \
        obs-studio \
        obsidian \
        signal-desktop \
        slack-desktop \
        spotify \
        sushi \
        teams-for-linux \
        typora \
        vlc \
        webcord \
        xournalpp \
        zoom
