#!/usr/bin/env bash

set -oue pipefail

source "$(dirname "$0")/../utils"

yay -S --noconfirm --needed \
        1password \
        evince \
        file-roller \
        gnome-calculator \
        libreoffice-fresh \
        nautilus \
        obs-studio \
        obsidian \
        signal-desktop \
        slack-desktop \
        spotify \
        sushi \
        teams-for-linux \
        typora \
        vlc \
        webcord \
        xournalpp \
        zoom

sudo mkdir -p /etc/1password
cat <<EOF | sudo tee /etc/1password/custom_allowed_browsers >/dev/null
vivaldi-bin
EOF
