#!/usr/bin/env bash

set -oue pipefail

# Clean package cache
paccache -r -k 2 2>/dev/null || true

# Remove orphan packages
yay -Qtdq | yay -Rns -

# Update mlocate database
updatedb 2>/dev/null || true
