#!/usr/bin/env bash

set -oue pipefail

# Clean package cache
paccache -r -k 2 2>/dev/null || true

# Remove orphan packages
orphans=$(yay -Qtdq) || true
if [[ -n "$orphans" ]]; then
        echo "$orphans" | yay -Rns -
fi

# Update mlocate database
updatedb 2>/dev/null || true
