#!/usr/bin/env bash

set -euo pipefail

if ! command -v bat &>/dev/null; then
	echo "$(bat) is not installed"
	exit 1
fi

if ! command -v curl &>/dev/null; then
	echo "$(curl) must be installed to update $(bat) themes"
fi

mkdir -p "$(bat --config-dir)/themes"
curl -LO --output-dir "$(bat --config-dir)/themes" https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/sublime/tokyonight_storm.tmTheme
bat cache --build
