#!/usr/bin/env bash

set -euo pipefail

if ! command -v bat &>/dev/null; then
        echo "$(bat) is not installed"
        exit 1
fi

if ! command -v curl &>/dev/null; then
        echo "$(curl) must be installed to update $(bat) themes"
fi

THEMES_DIR="$(bat --config-dir)/themes"

mkdir -p "$THEMES_DIR"

for variant in day moon night storm; do
        curl -LO --output-dir "$THEMES_DIR" "https://raw.githubusercontent.com/joshuadavidthomas/tokyonight.nvim/main/extras/sublime/tokyonight_${variant}.tmTheme"
done

bat cache --build
