alias claude="env CLAUDE_CONFIG_DIR=$HOME/.claude $HOME/.claude/local/claude"
alias fabric="fabric-ai"
alias lg="lazygit"
alias j="just --justfile ~/.justfile --working-directory ."
alias vim="nvim"

# alias sp="spotify_player"

# shadow cat="bat --paging=never"
# shadow find="fd"
# shadow ls="eza"
# shadow l="eza --long --all --group-directories-first --git-ignore"
# shadow la="eza --long --all --git"
# shadow ll="eza --long --all --group-directories-first --git"
# shadow lt="eza --tree --git-ignore --level=2 --group-directories-first"
# shadow llt="eza --long --tree --git-ignore --level=2 --group-directories-first"
# shadow lT="eza --tree --git-ignore --level=4 --group-directories-first"
# shadow top="btop"
# shadow tree="eza --tree"
# shadow vim="nvim"
