alias lg="lazygit"

# shadow cat="bat --paging=never"
# shadow find="fd"
# shadow ls="eza"
# shadow l="eza --long --all --group-directories-first --git-ignore"
# shadow la="eza --long --all --git"
# shadow ll="eza --long --all --group-directories-first --git"
# shadow lt="eza --tree --git-ignore --level=2 --group-directories-first"
# shadow llt="eza --long --tree --git-ignore --level=2 --group-directories-first"
# shadow lT="eza --tree --git-ignore --level=4 --group-directories-first"
# shadow top="btop"
# shadow tree="eza --tree"
# shadow vim="nvim"
