mode = "local"
project = ""
shell = ""

[dirs]
project = []
python = "isolated"
data = "/home/josh/.local/share/hatch"
cache = "/home/josh/.cache/hatch"

[dirs.env]

[projects]

[publish.index]
user = ""
auth = ""

[template]
name = "Josh"
email = "josh@joshthomas.dev"

[template.licenses]
headers = true
default = [
    "MIT",
]

[template.plugins.default]
tests = true
ci = false
src-layout = false

[terminal.styles]
info = "bold"
success = "bold cyan"
error = "bold red"
warning = "bold yellow"
waiting = "bold magenta"
debug = "bold"
spinner = "simpleDotsScrolling"
