#!/usr/bin/env bash

if [[ -f .env ]] && command dotenv-linter --version >&/dev/null; then
  dotenv-linter .env || log_error 'ERROR|https://dotenv-linter.github.io'
fi

dotenv_if_exists || direnv status # https://direnv.net/man/direnv-stdlib.1.html
