#!/usr/bin/env bash

set -oue pipefail

yadm gitconfig core.sparseCheckout true
yadm sparse-checkout set \
        '/*' \
        '!.github/' \
        '!LICENSE' \
        '!README.md' \
        '!install'
