[[themes]]
name = "Tokyo Night Day"

[themes.palette]
background = "#d0d5e3"
foreground = "#6172b0"
black = "#a1a6c5"
red = "#f52a65"
green = "#587539"
yellow = "#8c6c3e"
blue = "#2e7de9"
magenta = "#9854f1"
cyan = "#007197"
white = "#6172b0"
bright_black = "#e1e2e7"
bright_red = "#c64343"
bright_green = "#387068"
bright_yellow = "#b15c00"
bright_blue = "#188092"
bright_magenta = "#d20065"
bright_cyan = "#006a83"
bright_white = "#3760bf"

[[themes]]
name = "Tokyo Night Moon"

[themes.palette]
background = "#1e2030"
foreground = "#828bb8"
black = "#444a73"
red = "#ff757f"
green = "#c3e88d"
yellow = "#ffc777"
blue = "#82aaff"
magenta = "#c099ff"
cyan = "#86e1fc"
white = "#828bb8"
bright_black = "#222436"
bright_red = "#c53b53"
bright_green = "#4fd6be"
bright_yellow = "#ff966c"
bright_blue = "#65bcff"
bright_magenta = "#ff007c"
bright_cyan = "#89ddff"
bright_white = "#c8d3f5"

[[themes]]
name = "Tokyo Night"

[themes.palette]
background = "#16161e"
foreground = "#a9b1d6"
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"
bright_black = "#1a1b26"
bright_red = "#db4b4b"
bright_green = "#73daca"
bright_yellow = "#ff9e64"
bright_blue = "#2ac3de"
bright_magenta = "#ff007c"
bright_cyan = "#89ddff"
bright_white = "#c0caf5"


[[themes]]
name = "Tokyo Night Storm"

[themes.palette]
background = "#1f2335"
foreground = "#a9b1d6"
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"
bright_black = "#24283b"
bright_red = "#db4b4b"
bright_green = "#73daca"
bright_yellow = "#ff9e64"
bright_blue = "#2ac3de"
bright_magenta = "#ff007c"
bright_cyan = "#89ddff"
bright_white = "#c0caf5"
