[tools]
bun = "latest"
erlang = "latest"
go = "latest"
lua = "latest"
node = "lts"
usage = "latest"

"aqua:gleam-lang/gleam" = "latest"
"npm:@openai/codex" = "latest"
"npm:pake-cli" = "latest"
"npm:neovim" = "latest"
"npm:smee-client" = "latest"
"pipx:tldr" = "latest"

[settings]
disable_tools = [
  "python",
  "rust",
]
experimental = true

[settings.npm]
bun = true

[settings.pipx]
uvx = true

[settings.python]
uv_venv_auto = true
