[tools]
go = "latest"
lua = "latest"
node = "lts"
usage = "latest"
bun = "latest"
"npm:pake-cli" = "latest"
"npm:smee-client" = "latest"
"npm:neovim" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"

[settings]
experimental = true
